Add fd isntallation

diff --git a/run_once_install_packages.sh.tmpl b/run_once_install_packages.sh.tmpl
--- a/run_once_install_packages.sh.tmpl
+++ b/run_once_install_packages.sh.tmpl
@@ -35,4 +35,14 @@ then
 	fi
 fi
 
+# check fd 
+if ! command -v fd ; then
+	( 
+	wget https://github.com/sharkdp/fd/releases/download/v8.3.2/fd-v8.3.2-x86_64-unknown-linux-musl.tar.gz -P ~/Downloads/
+	mkdir -p ~/bin/fd-folder
+	tar xvfz ~/Downloads/fd-v8.3.2-x86_64-unknown-linux-musl.tar.gz -C ~/bin/fd-folder	
+	ln -s ~/bin/fd-folder/fd-v8.3.2-x86_64-unknown-linux-musl/fd ~/bin/fd
+	) || echo "fd install failed"
+fi
+
 {{ end -}}
