Add neovim install and vim config

diff --git a/run_once_install_packages.sh.tmpl b/run_once_install_packages.sh.tmpl
--- a/run_once_install_packages.sh.tmpl
+++ b/run_once_install_packages.sh.tmpl
@@ -73,4 +73,13 @@ if ! command -v node ; then
 	) || echo "node install failed" 
 fi
 
+# check neovim
+if ! command -v nvim ; then
+	(
+	wget https://github.com/neovim/neovim/releases/latest/download/nvim.appimage -P ~/bin/
+	cd ~/bin
+	chmod u+x nvim.appimage
+	ln -s nvim.appimage nvim
+	) || echo "neovim install failed [❌]"
+fi
 {{ end -}}
