[zoxide, ranger] ranger-zoxide plugin and mapping

diff --git a/run_once_install_packages.sh.tmpl b/run_once_install_packages.sh.tmpl
--- a/run_once_install_packages.sh.tmpl
+++ b/run_once_install_packages.sh.tmpl
@@ -106,4 +106,10 @@ if command -v zoxide ; then
 	) || echo  "zoxide install failed [❌]"
 fi
 
+# ranger-zoxide plugin
+if command -v ranger && command -v zoxide ; then
+	(
+	[[ ! -d ~/.config/ranger/plugins/zoxide ]] && git clone https://github.com/jchook/ranger-zoxide.git ~/.config/ranger/plugins/zoxide
+	) || echo  "ranger-zoxide install failed [❌]"
+fi
 {{ end -}}
