[zoxide] Install

diff --git a/run_once_install_packages.sh.tmpl b/run_once_install_packages.sh.tmpl
--- a/run_once_install_packages.sh.tmpl
+++ b/run_once_install_packages.sh.tmpl
@@ -99,4 +99,11 @@ if command -v ranger ; then
 	) || echo  "ranger_tmux install failed [❌]"
 fi
 
+# zoxide
+if command -v zoxide ; then
+	(
+	curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
+	) || echo  "zoxide install failed [❌]"
+fi
+
 {{ end -}}
