Add fzf

diff --git a/run_once_install_packages.sh.tmpl b/run_once_install_packages.sh.tmpl
--- a/run_once_install_packages.sh.tmpl
+++ b/run_once_install_packages.sh.tmpl
@@ -45,4 +45,14 @@ if ! command -v fd ; then
 	) || echo "fd install failed"
 fi
 
+# check fzf 
+if ! command -v fzf ; then
+	( 
+	wget https://github.com/junegunn/fzf/releases/download/0.30.0/fzf-0.30.0-linux_amd64.tar.gz -P ~/Downloads/
+	mkdir -p ~/bin/fzf-folder
+	tar xvfz ~/Downloads/fzf-0.30.0-linux_amd64.tar.gz -C ~/bin/fzf-folder	
+	ln -s ~/bin/fzf-folder/fzf ~/bin/fzf
+	) || echo "fzf install failed"
+fi
+
 {{ end -}}
