Install nvm and nodejs

diff --git a/run_once_install_packages.sh.tmpl b/run_once_install_packages.sh.tmpl
--- a/run_once_install_packages.sh.tmpl
+++ b/run_once_install_packages.sh.tmpl
@@ -55,4 +55,22 @@ if ! command -v fzf ; then
 	) || echo "fzf install failed"
 fi
 
+# check nvm
+if ! command -v nvm ; then
+	( 
+	wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | PROFILE="/dev/null" bash 
+
+	) || echo "nvm install failed" 
+	
+	export NVM_DIR="$HOME/.nvm"
+	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
+	[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
+fi
+# check nodeJs
+if ! command -v node ; then
+	( 
+	nvm use 14 || nvm install 14 ; nvm use 14 	
+	) || echo "node install failed" 
+fi
+
 {{ end -}}
